#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 108
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 13
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 13

enum {
  anon_sym_LF = 1,
  anon_sym_SEMI = 2,
  anon_sym_let = 3,
  anon_sym_EQ = 4,
  anon_sym_return = 5,
  anon_sym_if = 6,
  anon_sym_LPAREN = 7,
  anon_sym_RPAREN = 8,
  anon_sym_else = 9,
  anon_sym_PLUS = 10,
  anon_sym_DASH = 11,
  anon_sym_BANG = 12,
  anon_sym_STAR = 13,
  anon_sym_SLASH = 14,
  anon_sym_LT_EQ = 15,
  anon_sym_LT = 16,
  anon_sym_GT = 17,
  anon_sym_GT_EQ = 18,
  anon_sym_EQ_EQ = 19,
  anon_sym_BANG_EQ = 20,
  anon_sym_COMMA = 21,
  anon_sym_LBRACE = 22,
  anon_sym_RBRACE = 23,
  anon_sym_fn = 24,
  sym_true = 25,
  sym_false = 26,
  sym_identifier = 27,
  sym_number = 28,
  anon_sym_DQUOTE = 29,
  sym_source_file = 30,
  sym__statement = 31,
  sym_let_statement = 32,
  sym_return_statement = 33,
  sym_expression_statement = 34,
  sym__expression = 35,
  sym_if_expression = 36,
  sym_prefix_expression = 37,
  sym_binary_expression = 38,
  sym_parameter_list = 39,
  sym_parameter_declaration = 40,
  sym_block_statement = 41,
  sym__statement_list = 42,
  sym_function_literal = 43,
  sym_call_expression = 44,
  sym_argument_list = 45,
  sym_parenthesized_expression = 46,
  aux_sym_source_file_repeat1 = 47,
  aux_sym_parameter_list_repeat1 = 48,
  aux_sym_parameter_declaration_repeat1 = 49,
  aux_sym__statement_list_repeat1 = 50,
  aux_sym_argument_list_repeat1 = 51,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_SEMI] = ";",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_return] = "return",
  [anon_sym_if] = "if",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_else] = "else",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_BANG] = "!",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_fn] = "fn",
  [sym_true] = "true",
  [sym_false] = "false",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_let_statement] = "let_statement",
  [sym_return_statement] = "return_statement",
  [sym_expression_statement] = "expression_statement",
  [sym__expression] = "_expression",
  [sym_if_expression] = "if_expression",
  [sym_prefix_expression] = "prefix_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_parameter_list] = "parameter_list",
  [sym_parameter_declaration] = "parameter_declaration",
  [sym_block_statement] = "block_statement",
  [sym__statement_list] = "_statement_list",
  [sym_function_literal] = "function_literal",
  [sym_call_expression] = "call_expression",
  [sym_argument_list] = "argument_list",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_parameter_declaration_repeat1] = "parameter_declaration_repeat1",
  [aux_sym__statement_list_repeat1] = "_statement_list_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_fn] = anon_sym_fn,
  [sym_true] = sym_true,
  [sym_false] = sym_false,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_let_statement] = sym_let_statement,
  [sym_return_statement] = sym_return_statement,
  [sym_expression_statement] = sym_expression_statement,
  [sym__expression] = sym__expression,
  [sym_if_expression] = sym_if_expression,
  [sym_prefix_expression] = sym_prefix_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_parameter_list] = sym_parameter_list,
  [sym_parameter_declaration] = sym_parameter_declaration,
  [sym_block_statement] = sym_block_statement,
  [sym__statement_list] = sym__statement_list,
  [sym_function_literal] = sym_function_literal,
  [sym_call_expression] = sym_call_expression,
  [sym_argument_list] = sym_argument_list,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_parameter_declaration_repeat1] = aux_sym_parameter_declaration_repeat1,
  [aux_sym__statement_list_repeat1] = aux_sym__statement_list_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [sym_true] = {
    .visible = true,
    .named = true,
  },
  [sym_false] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_let_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_if_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_prefix_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_block_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__statement_list] = {
    .visible = false,
    .named = true,
  },
  [sym_function_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_call_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__statement_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_alternative = 1,
  field_arguments = 2,
  field_body = 3,
  field_condition = 4,
  field_consequence = 5,
  field_function = 6,
  field_left = 7,
  field_name = 8,
  field_operand = 9,
  field_operator = 10,
  field_parameters = 11,
  field_right = 12,
  field_value = 13,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alternative] = "alternative",
  [field_arguments] = "arguments",
  [field_body] = "body",
  [field_condition] = "condition",
  [field_consequence] = "consequence",
  [field_function] = "function",
  [field_left] = "left",
  [field_name] = "name",
  [field_operand] = "operand",
  [field_operator] = "operator",
  [field_parameters] = "parameters",
  [field_right] = "right",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 1},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 3},
  [7] = {.index = 11, .length = 2},
  [8] = {.index = 13, .length = 2},
  [9] = {.index = 15, .length = 2},
  [10] = {.index = 17, .length = 1},
  [11] = {.index = 18, .length = 2},
  [12] = {.index = 20, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_value, 1},
  [1] =
    {field_operand, 1},
    {field_operator, 0},
  [3] =
    {field_arguments, 1},
    {field_function, 0},
  [5] =
    {field_name, 0},
  [6] =
    {field_body, 2},
    {field_parameters, 1},
  [8] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [11] =
    {field_name, 1},
    {field_value, 3},
  [13] =
    {field_name, 0},
    {field_name, 1, .inherited = true},
  [15] =
    {field_condition, 2},
    {field_consequence, 4},
  [17] =
    {field_name, 1},
  [18] =
    {field_name, 0, .inherited = true},
    {field_name, 1, .inherited = true},
  [20] =
    {field_alternative, 6},
    {field_condition, 2},
    {field_consequence, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 3,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 9,
  [11] = 11,
  [12] = 12,
  [13] = 11,
  [14] = 12,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 16,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 20,
  [24] = 22,
  [25] = 25,
  [26] = 25,
  [27] = 21,
  [28] = 19,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 32,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 37,
  [43] = 43,
  [44] = 33,
  [45] = 41,
  [46] = 40,
  [47] = 38,
  [48] = 36,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 34,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 58,
  [61] = 53,
  [62] = 54,
  [63] = 57,
  [64] = 51,
  [65] = 59,
  [66] = 66,
  [67] = 49,
  [68] = 50,
  [69] = 55,
  [70] = 56,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 78,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 89,
  [92] = 86,
  [93] = 85,
  [94] = 94,
  [95] = 90,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 98,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 106,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      if (lookahead == '!') ADVANCE(26);
      if (lookahead == '"') ADVANCE(61);
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == ')') ADVANCE(20);
      if (lookahead == '*') ADVANCE(27);
      if (lookahead == '+') ADVANCE(23);
      if (lookahead == ',') ADVANCE(35);
      if (lookahead == '-') ADVANCE(24);
      if (lookahead == '/') ADVANCE(28);
      if (lookahead == ';') ADVANCE(13);
      if (lookahead == '<') ADVANCE(30);
      if (lookahead == '=') ADVANCE(16);
      if (lookahead == '>') ADVANCE(31);
      if (lookahead == 'e') ADVANCE(48);
      if (lookahead == 'f') ADVANCE(41);
      if (lookahead == 'i') ADVANCE(47);
      if (lookahead == 'l') ADVANCE(42);
      if (lookahead == 'r') ADVANCE(46);
      if (lookahead == 't') ADVANCE(51);
      if (lookahead == '{') ADVANCE(36);
      if (lookahead == '}') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead == '!') ADVANCE(5);
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == '*') ADVANCE(27);
      if (lookahead == '+') ADVANCE(23);
      if (lookahead == '-') ADVANCE(24);
      if (lookahead == '/') ADVANCE(28);
      if (lookahead == ';') ADVANCE(13);
      if (lookahead == '<') ADVANCE(30);
      if (lookahead == '=') ADVANCE(6);
      if (lookahead == '>') ADVANCE(31);
      if (lookahead == 'e') ADVANCE(8);
      if (lookahead == '}') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(25);
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == ')') ADVANCE(20);
      if (lookahead == '+') ADVANCE(23);
      if (lookahead == '-') ADVANCE(24);
      if (lookahead == 'f') ADVANCE(41);
      if (lookahead == 'i') ADVANCE(47);
      if (lookahead == 't') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 3:
      if (lookahead == '!') ADVANCE(5);
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == ')') ADVANCE(20);
      if (lookahead == '*') ADVANCE(27);
      if (lookahead == '+') ADVANCE(23);
      if (lookahead == ',') ADVANCE(35);
      if (lookahead == '-') ADVANCE(24);
      if (lookahead == '/') ADVANCE(28);
      if (lookahead == '<') ADVANCE(30);
      if (lookahead == '=') ADVANCE(6);
      if (lookahead == '>') ADVANCE(31);
      if (lookahead == 'e') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      END_STATE();
    case 4:
      if (lookahead == ')') ADVANCE(20);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(34);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(33);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 8:
      if (lookahead == 'l') ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == 's') ADVANCE(7);
      END_STATE();
    case 10:
      if (eof) ADVANCE(11);
      if (lookahead == '!') ADVANCE(25);
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == '+') ADVANCE(23);
      if (lookahead == '-') ADVANCE(24);
      if (lookahead == '=') ADVANCE(15);
      if (lookahead == 'f') ADVANCE(41);
      if (lookahead == 'i') ADVANCE(47);
      if (lookahead == 'l') ADVANCE(42);
      if (lookahead == 'r') ADVANCE(46);
      if (lookahead == 't') ADVANCE(51);
      if (lookahead == '}') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(10)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_let);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(33);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_return);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_if);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_else);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(34);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(29);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_fn);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_true);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_false);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(49);
      if (lookahead == 'n') ADVANCE(38);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(39);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(56);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(18);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(53);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(54);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(17);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(58);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(50);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(43);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(45);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(57);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(44);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 10},
  [2] = {.lex_state = 10},
  [3] = {.lex_state = 10},
  [4] = {.lex_state = 10},
  [5] = {.lex_state = 10},
  [6] = {.lex_state = 10},
  [7] = {.lex_state = 10},
  [8] = {.lex_state = 10},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 3},
  [61] = {.lex_state = 3},
  [62] = {.lex_state = 3},
  [63] = {.lex_state = 3},
  [64] = {.lex_state = 3},
  [65] = {.lex_state = 3},
  [66] = {.lex_state = 10},
  [67] = {.lex_state = 3},
  [68] = {.lex_state = 3},
  [69] = {.lex_state = 3},
  [70] = {.lex_state = 3},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 4},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 4},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 1},
  [97] = {.lex_state = 10},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 4},
  [104] = {.lex_state = 4},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [sym_true] = ACTIONS(1),
    [sym_false] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(101),
    [sym__statement] = STATE(96),
    [sym_let_statement] = STATE(96),
    [sym_return_statement] = STATE(96),
    [sym_expression_statement] = STATE(96),
    [sym__expression] = STATE(31),
    [sym_if_expression] = STATE(31),
    [sym_prefix_expression] = STATE(31),
    [sym_binary_expression] = STATE(31),
    [sym_function_literal] = STATE(31),
    [sym_call_expression] = STATE(31),
    [sym_parenthesized_expression] = STATE(31),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_let] = ACTIONS(5),
    [anon_sym_return] = ACTIONS(7),
    [anon_sym_if] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_PLUS] = ACTIONS(13),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(13),
    [anon_sym_fn] = ACTIONS(15),
    [sym_true] = ACTIONS(17),
    [sym_false] = ACTIONS(17),
    [sym_identifier] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_return,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      sym_number,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(13), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(17), 3,
      sym_true,
      sym_false,
      sym_identifier,
    STATE(96), 4,
      sym__statement,
      sym_let_statement,
      sym_return_statement,
      sym_expression_statement,
    STATE(31), 7,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_binary_expression,
      sym_function_literal,
      sym_call_expression,
      sym_parenthesized_expression,
  [50] = 12,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_return,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      sym_number,
    ACTIONS(23), 1,
      anon_sym_RBRACE,
    STATE(102), 1,
      sym__statement_list,
    ACTIONS(13), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(17), 3,
      sym_true,
      sym_false,
      sym_identifier,
    STATE(71), 4,
      sym__statement,
      sym_let_statement,
      sym_return_statement,
      sym_expression_statement,
    STATE(31), 7,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_binary_expression,
      sym_function_literal,
      sym_call_expression,
      sym_parenthesized_expression,
  [100] = 12,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      anon_sym_let,
    ACTIONS(30), 1,
      anon_sym_return,
    ACTIONS(33), 1,
      anon_sym_if,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(42), 1,
      anon_sym_fn,
    ACTIONS(48), 1,
      sym_number,
    STATE(4), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(39), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(45), 3,
      sym_true,
      sym_false,
      sym_identifier,
    STATE(96), 4,
      sym__statement,
      sym_let_statement,
      sym_return_statement,
      sym_expression_statement,
    STATE(31), 7,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_binary_expression,
      sym_function_literal,
      sym_call_expression,
      sym_parenthesized_expression,
  [150] = 12,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_return,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      sym_number,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    STATE(98), 1,
      sym__statement_list,
    ACTIONS(13), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(17), 3,
      sym_true,
      sym_false,
      sym_identifier,
    STATE(71), 4,
      sym__statement,
      sym_let_statement,
      sym_return_statement,
      sym_expression_statement,
    STATE(31), 7,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_binary_expression,
      sym_function_literal,
      sym_call_expression,
      sym_parenthesized_expression,
  [200] = 11,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_return,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      sym_number,
    ACTIONS(53), 1,
      anon_sym_RBRACE,
    ACTIONS(13), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(17), 3,
      sym_true,
      sym_false,
      sym_identifier,
    STATE(75), 4,
      sym__statement,
      sym_let_statement,
      sym_return_statement,
      sym_expression_statement,
    STATE(31), 7,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_binary_expression,
      sym_function_literal,
      sym_call_expression,
      sym_parenthesized_expression,
  [247] = 11,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_return,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      sym_number,
    ACTIONS(55), 1,
      anon_sym_RBRACE,
    ACTIONS(13), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(17), 3,
      sym_true,
      sym_false,
      sym_identifier,
    STATE(75), 4,
      sym__statement,
      sym_let_statement,
      sym_return_statement,
      sym_expression_statement,
    STATE(31), 7,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_binary_expression,
      sym_function_literal,
      sym_call_expression,
      sym_parenthesized_expression,
  [294] = 10,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_return,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      sym_number,
    ACTIONS(13), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(17), 3,
      sym_true,
      sym_false,
      sym_identifier,
    STATE(75), 4,
      sym__statement,
      sym_let_statement,
      sym_return_statement,
      sym_expression_statement,
    STATE(31), 7,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_binary_expression,
      sym_function_literal,
      sym_call_expression,
      sym_parenthesized_expression,
  [338] = 8,
    ACTIONS(57), 1,
      anon_sym_if,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 1,
      anon_sym_RPAREN,
    ACTIONS(65), 1,
      anon_sym_fn,
    ACTIONS(69), 1,
      sym_number,
    ACTIONS(63), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(67), 3,
      sym_true,
      sym_false,
      sym_identifier,
    STATE(35), 7,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_binary_expression,
      sym_function_literal,
      sym_call_expression,
      sym_parenthesized_expression,
  [373] = 8,
    ACTIONS(57), 1,
      anon_sym_if,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      anon_sym_fn,
    ACTIONS(71), 1,
      anon_sym_RPAREN,
    ACTIONS(75), 1,
      sym_number,
    ACTIONS(63), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(73), 3,
      sym_true,
      sym_false,
      sym_identifier,
    STATE(32), 7,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_binary_expression,
      sym_function_literal,
      sym_call_expression,
      sym_parenthesized_expression,
  [408] = 8,
    ACTIONS(57), 1,
      anon_sym_if,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      anon_sym_fn,
    ACTIONS(77), 1,
      anon_sym_RPAREN,
    ACTIONS(81), 1,
      sym_number,
    ACTIONS(63), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(79), 3,
      sym_true,
      sym_false,
      sym_identifier,
    STATE(43), 7,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_binary_expression,
      sym_function_literal,
      sym_call_expression,
      sym_parenthesized_expression,
  [443] = 8,
    ACTIONS(57), 1,
      anon_sym_if,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      anon_sym_fn,
    ACTIONS(81), 1,
      sym_number,
    ACTIONS(83), 1,
      anon_sym_RPAREN,
    ACTIONS(63), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(79), 3,
      sym_true,
      sym_false,
      sym_identifier,
    STATE(43), 7,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_binary_expression,
      sym_function_literal,
      sym_call_expression,
      sym_parenthesized_expression,
  [478] = 8,
    ACTIONS(57), 1,
      anon_sym_if,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      anon_sym_fn,
    ACTIONS(81), 1,
      sym_number,
    ACTIONS(85), 1,
      anon_sym_RPAREN,
    ACTIONS(63), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(79), 3,
      sym_true,
      sym_false,
      sym_identifier,
    STATE(43), 7,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_binary_expression,
      sym_function_literal,
      sym_call_expression,
      sym_parenthesized_expression,
  [513] = 8,
    ACTIONS(57), 1,
      anon_sym_if,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      anon_sym_fn,
    ACTIONS(81), 1,
      sym_number,
    ACTIONS(87), 1,
      anon_sym_RPAREN,
    ACTIONS(63), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(79), 3,
      sym_true,
      sym_false,
      sym_identifier,
    STATE(43), 7,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_binary_expression,
      sym_function_literal,
      sym_call_expression,
      sym_parenthesized_expression,
  [548] = 7,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_fn,
    ACTIONS(91), 1,
      sym_number,
    ACTIONS(13), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(89), 3,
      sym_true,
      sym_false,
      sym_identifier,
    STATE(39), 7,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_binary_expression,
      sym_function_literal,
      sym_call_expression,
      sym_parenthesized_expression,
  [580] = 7,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_fn,
    ACTIONS(95), 1,
      sym_number,
    ACTIONS(13), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(93), 3,
      sym_true,
      sym_false,
      sym_identifier,
    STATE(34), 7,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_binary_expression,
      sym_function_literal,
      sym_call_expression,
      sym_parenthesized_expression,
  [612] = 7,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_fn,
    ACTIONS(99), 1,
      sym_number,
    ACTIONS(13), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(97), 3,
      sym_true,
      sym_false,
      sym_identifier,
    STATE(30), 7,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_binary_expression,
      sym_function_literal,
      sym_call_expression,
      sym_parenthesized_expression,
  [644] = 7,
    ACTIONS(57), 1,
      anon_sym_if,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      anon_sym_fn,
    ACTIONS(103), 1,
      sym_number,
    ACTIONS(63), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(101), 3,
      sym_true,
      sym_false,
      sym_identifier,
    STATE(52), 7,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_binary_expression,
      sym_function_literal,
      sym_call_expression,
      sym_parenthesized_expression,
  [676] = 7,
    ACTIONS(57), 1,
      anon_sym_if,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      anon_sym_fn,
    ACTIONS(107), 1,
      sym_number,
    ACTIONS(63), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(105), 3,
      sym_true,
      sym_false,
      sym_identifier,
    STATE(59), 7,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_binary_expression,
      sym_function_literal,
      sym_call_expression,
      sym_parenthesized_expression,
  [708] = 7,
    ACTIONS(57), 1,
      anon_sym_if,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      anon_sym_fn,
    ACTIONS(111), 1,
      sym_number,
    ACTIONS(63), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(109), 3,
      sym_true,
      sym_false,
      sym_identifier,
    STATE(47), 7,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_binary_expression,
      sym_function_literal,
      sym_call_expression,
      sym_parenthesized_expression,
  [740] = 7,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_fn,
    ACTIONS(115), 1,
      sym_number,
    ACTIONS(13), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(113), 3,
      sym_true,
      sym_false,
      sym_identifier,
    STATE(36), 7,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_binary_expression,
      sym_function_literal,
      sym_call_expression,
      sym_parenthesized_expression,
  [772] = 7,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_fn,
    ACTIONS(119), 1,
      sym_number,
    ACTIONS(13), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(117), 3,
      sym_true,
      sym_false,
      sym_identifier,
    STATE(37), 7,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_binary_expression,
      sym_function_literal,
      sym_call_expression,
      sym_parenthesized_expression,
  [804] = 7,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_fn,
    ACTIONS(123), 1,
      sym_number,
    ACTIONS(13), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(121), 3,
      sym_true,
      sym_false,
      sym_identifier,
    STATE(38), 7,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_binary_expression,
      sym_function_literal,
      sym_call_expression,
      sym_parenthesized_expression,
  [836] = 7,
    ACTIONS(57), 1,
      anon_sym_if,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      anon_sym_fn,
    ACTIONS(127), 1,
      sym_number,
    ACTIONS(63), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(125), 3,
      sym_true,
      sym_false,
      sym_identifier,
    STATE(42), 7,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_binary_expression,
      sym_function_literal,
      sym_call_expression,
      sym_parenthesized_expression,
  [868] = 7,
    ACTIONS(57), 1,
      anon_sym_if,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      anon_sym_fn,
    ACTIONS(131), 1,
      sym_number,
    ACTIONS(63), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(129), 3,
      sym_true,
      sym_false,
      sym_identifier,
    STATE(58), 7,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_binary_expression,
      sym_function_literal,
      sym_call_expression,
      sym_parenthesized_expression,
  [900] = 7,
    ACTIONS(57), 1,
      anon_sym_if,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      anon_sym_fn,
    ACTIONS(135), 1,
      sym_number,
    ACTIONS(63), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(133), 3,
      sym_true,
      sym_false,
      sym_identifier,
    STATE(60), 7,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_binary_expression,
      sym_function_literal,
      sym_call_expression,
      sym_parenthesized_expression,
  [932] = 7,
    ACTIONS(57), 1,
      anon_sym_if,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      anon_sym_fn,
    ACTIONS(139), 1,
      sym_number,
    ACTIONS(63), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(137), 3,
      sym_true,
      sym_false,
      sym_identifier,
    STATE(48), 7,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_binary_expression,
      sym_function_literal,
      sym_call_expression,
      sym_parenthesized_expression,
  [964] = 7,
    ACTIONS(57), 1,
      anon_sym_if,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      anon_sym_fn,
    ACTIONS(143), 1,
      sym_number,
    ACTIONS(63), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(141), 3,
      sym_true,
      sym_false,
      sym_identifier,
    STATE(65), 7,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_binary_expression,
      sym_function_literal,
      sym_call_expression,
      sym_parenthesized_expression,
  [996] = 7,
    ACTIONS(57), 1,
      anon_sym_if,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      anon_sym_fn,
    ACTIONS(81), 1,
      sym_number,
    ACTIONS(63), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(79), 3,
      sym_true,
      sym_false,
      sym_identifier,
    STATE(43), 7,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_binary_expression,
      sym_function_literal,
      sym_call_expression,
      sym_parenthesized_expression,
  [1028] = 7,
    ACTIONS(145), 1,
      anon_sym_LF,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    STATE(49), 1,
      sym_argument_list,
    ACTIONS(147), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(155), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(151), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(153), 4,
      anon_sym_LT_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_GT_EQ,
  [1058] = 7,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(157), 1,
      anon_sym_LF,
    STATE(49), 1,
      sym_argument_list,
    ACTIONS(155), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(159), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(151), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(153), 4,
      anon_sym_LT_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_GT_EQ,
  [1088] = 9,
    ACTIONS(161), 1,
      anon_sym_LPAREN,
    ACTIONS(163), 1,
      anon_sym_RPAREN,
    ACTIONS(173), 1,
      anon_sym_COMMA,
    STATE(67), 1,
      sym_argument_list,
    STATE(78), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(167), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(169), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(171), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(165), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1122] = 2,
    ACTIONS(175), 1,
      anon_sym_LF,
    ACTIONS(177), 14,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_else,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RBRACE,
  [1142] = 4,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(179), 1,
      anon_sym_LF,
    STATE(49), 1,
      sym_argument_list,
    ACTIONS(181), 12,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RBRACE,
  [1166] = 9,
    ACTIONS(161), 1,
      anon_sym_LPAREN,
    ACTIONS(183), 1,
      anon_sym_RPAREN,
    ACTIONS(185), 1,
      anon_sym_COMMA,
    STATE(67), 1,
      sym_argument_list,
    STATE(81), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(167), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(169), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(171), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(165), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1200] = 4,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(187), 1,
      anon_sym_LF,
    STATE(49), 1,
      sym_argument_list,
    ACTIONS(189), 12,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RBRACE,
  [1224] = 5,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(187), 1,
      anon_sym_LF,
    STATE(49), 1,
      sym_argument_list,
    ACTIONS(151), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(189), 8,
      anon_sym_SEMI,
      anon_sym_LT_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RBRACE,
  [1250] = 6,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(187), 1,
      anon_sym_LF,
    STATE(49), 1,
      sym_argument_list,
    ACTIONS(151), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(153), 4,
      anon_sym_LT_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_GT_EQ,
    ACTIONS(189), 4,
      anon_sym_SEMI,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RBRACE,
  [1278] = 7,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(191), 1,
      anon_sym_LF,
    STATE(49), 1,
      sym_argument_list,
    ACTIONS(155), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(193), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(151), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(153), 4,
      anon_sym_LT_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_GT_EQ,
  [1308] = 2,
    ACTIONS(195), 1,
      anon_sym_LF,
    ACTIONS(197), 14,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_else,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RBRACE,
  [1328] = 3,
    ACTIONS(199), 1,
      anon_sym_LF,
    ACTIONS(203), 1,
      anon_sym_else,
    ACTIONS(201), 13,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RBRACE,
  [1350] = 5,
    ACTIONS(161), 1,
      anon_sym_LPAREN,
    STATE(67), 1,
      sym_argument_list,
    ACTIONS(189), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(165), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(187), 6,
      anon_sym_RPAREN,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_COMMA,
  [1375] = 7,
    ACTIONS(161), 1,
      anon_sym_LPAREN,
    STATE(67), 1,
      sym_argument_list,
    ACTIONS(167), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(169), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(171), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(205), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(165), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1404] = 2,
    ACTIONS(177), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(175), 12,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_else,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_COMMA,
  [1423] = 3,
    ACTIONS(207), 1,
      anon_sym_else,
    ACTIONS(201), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(199), 11,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_COMMA,
  [1444] = 2,
    ACTIONS(197), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(195), 12,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_else,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_COMMA,
  [1463] = 6,
    ACTIONS(161), 1,
      anon_sym_LPAREN,
    STATE(67), 1,
      sym_argument_list,
    ACTIONS(167), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(169), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(165), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(187), 4,
      anon_sym_RPAREN,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_COMMA,
  [1490] = 4,
    ACTIONS(161), 1,
      anon_sym_LPAREN,
    STATE(67), 1,
      sym_argument_list,
    ACTIONS(189), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(187), 10,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_COMMA,
  [1513] = 2,
    ACTIONS(209), 1,
      anon_sym_LF,
    ACTIONS(211), 13,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RBRACE,
  [1532] = 2,
    ACTIONS(213), 1,
      anon_sym_LF,
    ACTIONS(215), 13,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RBRACE,
  [1551] = 2,
    ACTIONS(217), 1,
      anon_sym_LF,
    ACTIONS(219), 13,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RBRACE,
  [1570] = 4,
    ACTIONS(161), 1,
      anon_sym_LPAREN,
    STATE(67), 1,
      sym_argument_list,
    ACTIONS(181), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(179), 10,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_COMMA,
  [1593] = 2,
    ACTIONS(221), 1,
      anon_sym_LF,
    ACTIONS(223), 13,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RBRACE,
  [1612] = 2,
    ACTIONS(225), 1,
      anon_sym_LF,
    ACTIONS(227), 13,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RBRACE,
  [1631] = 2,
    ACTIONS(229), 1,
      anon_sym_LF,
    ACTIONS(231), 13,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RBRACE,
  [1650] = 2,
    ACTIONS(233), 1,
      anon_sym_LF,
    ACTIONS(235), 13,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RBRACE,
  [1669] = 2,
    ACTIONS(237), 1,
      anon_sym_LF,
    ACTIONS(239), 13,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RBRACE,
  [1688] = 7,
    ACTIONS(161), 1,
      anon_sym_LPAREN,
    ACTIONS(241), 1,
      anon_sym_RPAREN,
    STATE(67), 1,
      sym_argument_list,
    ACTIONS(167), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(169), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(171), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(165), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1716] = 7,
    ACTIONS(161), 1,
      anon_sym_LPAREN,
    ACTIONS(243), 1,
      anon_sym_RPAREN,
    STATE(67), 1,
      sym_argument_list,
    ACTIONS(167), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(169), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(171), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(165), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1744] = 7,
    ACTIONS(161), 1,
      anon_sym_LPAREN,
    ACTIONS(245), 1,
      anon_sym_RPAREN,
    STATE(67), 1,
      sym_argument_list,
    ACTIONS(167), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(169), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(171), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(165), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1772] = 2,
    ACTIONS(223), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(221), 11,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_COMMA,
  [1790] = 2,
    ACTIONS(227), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(225), 11,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_COMMA,
  [1808] = 2,
    ACTIONS(239), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(237), 11,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_COMMA,
  [1826] = 2,
    ACTIONS(219), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(217), 11,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_COMMA,
  [1844] = 7,
    ACTIONS(161), 1,
      anon_sym_LPAREN,
    ACTIONS(247), 1,
      anon_sym_RPAREN,
    STATE(67), 1,
      sym_argument_list,
    ACTIONS(167), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(169), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(171), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(165), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1872] = 2,
    ACTIONS(25), 6,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
    ACTIONS(249), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      anon_sym_fn,
      sym_true,
      sym_false,
      sym_identifier,
  [1890] = 2,
    ACTIONS(211), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(209), 11,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_COMMA,
  [1908] = 2,
    ACTIONS(215), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(213), 11,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_COMMA,
  [1926] = 2,
    ACTIONS(231), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(229), 11,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_COMMA,
  [1944] = 2,
    ACTIONS(235), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(233), 11,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_COMMA,
  [1962] = 4,
    ACTIONS(251), 1,
      anon_sym_LF,
    ACTIONS(253), 1,
      anon_sym_SEMI,
    ACTIONS(255), 1,
      anon_sym_RBRACE,
    STATE(72), 1,
      aux_sym__statement_list_repeat1,
  [1975] = 4,
    ACTIONS(257), 1,
      anon_sym_LF,
    ACTIONS(259), 1,
      anon_sym_SEMI,
    ACTIONS(261), 1,
      anon_sym_RBRACE,
    STATE(73), 1,
      aux_sym__statement_list_repeat1,
  [1988] = 4,
    ACTIONS(263), 1,
      anon_sym_LF,
    ACTIONS(266), 1,
      anon_sym_SEMI,
    ACTIONS(269), 1,
      anon_sym_RBRACE,
    STATE(73), 1,
      aux_sym__statement_list_repeat1,
  [2001] = 3,
    ACTIONS(271), 1,
      anon_sym_RPAREN,
    ACTIONS(273), 1,
      anon_sym_COMMA,
    STATE(74), 1,
      aux_sym_parameter_declaration_repeat1,
  [2011] = 2,
    ACTIONS(276), 1,
      anon_sym_LF,
    ACTIONS(269), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2019] = 3,
    ACTIONS(278), 1,
      anon_sym_RPAREN,
    ACTIONS(280), 1,
      anon_sym_COMMA,
    STATE(76), 1,
      aux_sym_parameter_list_repeat1,
  [2029] = 2,
    STATE(84), 1,
      aux_sym_parameter_declaration_repeat1,
    ACTIONS(283), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [2037] = 3,
    ACTIONS(83), 1,
      anon_sym_RPAREN,
    ACTIONS(285), 1,
      anon_sym_COMMA,
    STATE(82), 1,
      aux_sym_argument_list_repeat1,
  [2047] = 3,
    ACTIONS(287), 1,
      anon_sym_RPAREN,
    ACTIONS(289), 1,
      sym_identifier,
    STATE(80), 1,
      sym_parameter_declaration,
  [2057] = 3,
    ACTIONS(291), 1,
      anon_sym_RPAREN,
    ACTIONS(293), 1,
      anon_sym_COMMA,
    STATE(83), 1,
      aux_sym_parameter_list_repeat1,
  [2067] = 3,
    ACTIONS(87), 1,
      anon_sym_RPAREN,
    ACTIONS(295), 1,
      anon_sym_COMMA,
    STATE(82), 1,
      aux_sym_argument_list_repeat1,
  [2077] = 3,
    ACTIONS(205), 1,
      anon_sym_RPAREN,
    ACTIONS(297), 1,
      anon_sym_COMMA,
    STATE(82), 1,
      aux_sym_argument_list_repeat1,
  [2087] = 3,
    ACTIONS(293), 1,
      anon_sym_COMMA,
    ACTIONS(300), 1,
      anon_sym_RPAREN,
    STATE(76), 1,
      aux_sym_parameter_list_repeat1,
  [2097] = 2,
    STATE(74), 1,
      aux_sym_parameter_declaration_repeat1,
    ACTIONS(302), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [2105] = 2,
    ACTIONS(304), 1,
      anon_sym_LBRACE,
    STATE(55), 1,
      sym_block_statement,
  [2112] = 2,
    ACTIONS(306), 1,
      anon_sym_LBRACE,
    STATE(45), 1,
      sym_block_statement,
  [2119] = 2,
    ACTIONS(289), 1,
      sym_identifier,
    STATE(88), 1,
      sym_parameter_declaration,
  [2126] = 1,
    ACTIONS(278), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [2131] = 2,
    ACTIONS(308), 1,
      anon_sym_LPAREN,
    STATE(93), 1,
      sym_parameter_list,
  [2138] = 2,
    ACTIONS(304), 1,
      anon_sym_LBRACE,
    STATE(53), 1,
      sym_block_statement,
  [2145] = 2,
    ACTIONS(308), 1,
      anon_sym_LPAREN,
    STATE(85), 1,
      sym_parameter_list,
  [2152] = 2,
    ACTIONS(304), 1,
      anon_sym_LBRACE,
    STATE(41), 1,
      sym_block_statement,
  [2159] = 2,
    ACTIONS(306), 1,
      anon_sym_LBRACE,
    STATE(69), 1,
      sym_block_statement,
  [2166] = 1,
    ACTIONS(310), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [2171] = 2,
    ACTIONS(306), 1,
      anon_sym_LBRACE,
    STATE(61), 1,
      sym_block_statement,
  [2178] = 2,
    ACTIONS(312), 1,
      anon_sym_LF,
    ACTIONS(314), 1,
      anon_sym_SEMI,
  [2185] = 1,
    ACTIONS(316), 1,
      anon_sym_EQ,
  [2189] = 1,
    ACTIONS(318), 1,
      anon_sym_RBRACE,
  [2193] = 1,
    ACTIONS(320), 1,
      anon_sym_LBRACE,
  [2197] = 1,
    ACTIONS(322), 1,
      anon_sym_LBRACE,
  [2201] = 1,
    ACTIONS(324), 1,
      ts_builtin_sym_end,
  [2205] = 1,
    ACTIONS(326), 1,
      anon_sym_RBRACE,
  [2209] = 1,
    ACTIONS(328), 1,
      sym_identifier,
  [2213] = 1,
    ACTIONS(330), 1,
      sym_identifier,
  [2217] = 1,
    ACTIONS(332), 1,
      anon_sym_LBRACE,
  [2221] = 1,
    ACTIONS(334), 1,
      anon_sym_LPAREN,
  [2225] = 1,
    ACTIONS(336), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 50,
  [SMALL_STATE(4)] = 100,
  [SMALL_STATE(5)] = 150,
  [SMALL_STATE(6)] = 200,
  [SMALL_STATE(7)] = 247,
  [SMALL_STATE(8)] = 294,
  [SMALL_STATE(9)] = 338,
  [SMALL_STATE(10)] = 373,
  [SMALL_STATE(11)] = 408,
  [SMALL_STATE(12)] = 443,
  [SMALL_STATE(13)] = 478,
  [SMALL_STATE(14)] = 513,
  [SMALL_STATE(15)] = 548,
  [SMALL_STATE(16)] = 580,
  [SMALL_STATE(17)] = 612,
  [SMALL_STATE(18)] = 644,
  [SMALL_STATE(19)] = 676,
  [SMALL_STATE(20)] = 708,
  [SMALL_STATE(21)] = 740,
  [SMALL_STATE(22)] = 772,
  [SMALL_STATE(23)] = 804,
  [SMALL_STATE(24)] = 836,
  [SMALL_STATE(25)] = 868,
  [SMALL_STATE(26)] = 900,
  [SMALL_STATE(27)] = 932,
  [SMALL_STATE(28)] = 964,
  [SMALL_STATE(29)] = 996,
  [SMALL_STATE(30)] = 1028,
  [SMALL_STATE(31)] = 1058,
  [SMALL_STATE(32)] = 1088,
  [SMALL_STATE(33)] = 1122,
  [SMALL_STATE(34)] = 1142,
  [SMALL_STATE(35)] = 1166,
  [SMALL_STATE(36)] = 1200,
  [SMALL_STATE(37)] = 1224,
  [SMALL_STATE(38)] = 1250,
  [SMALL_STATE(39)] = 1278,
  [SMALL_STATE(40)] = 1308,
  [SMALL_STATE(41)] = 1328,
  [SMALL_STATE(42)] = 1350,
  [SMALL_STATE(43)] = 1375,
  [SMALL_STATE(44)] = 1404,
  [SMALL_STATE(45)] = 1423,
  [SMALL_STATE(46)] = 1444,
  [SMALL_STATE(47)] = 1463,
  [SMALL_STATE(48)] = 1490,
  [SMALL_STATE(49)] = 1513,
  [SMALL_STATE(50)] = 1532,
  [SMALL_STATE(51)] = 1551,
  [SMALL_STATE(52)] = 1570,
  [SMALL_STATE(53)] = 1593,
  [SMALL_STATE(54)] = 1612,
  [SMALL_STATE(55)] = 1631,
  [SMALL_STATE(56)] = 1650,
  [SMALL_STATE(57)] = 1669,
  [SMALL_STATE(58)] = 1688,
  [SMALL_STATE(59)] = 1716,
  [SMALL_STATE(60)] = 1744,
  [SMALL_STATE(61)] = 1772,
  [SMALL_STATE(62)] = 1790,
  [SMALL_STATE(63)] = 1808,
  [SMALL_STATE(64)] = 1826,
  [SMALL_STATE(65)] = 1844,
  [SMALL_STATE(66)] = 1872,
  [SMALL_STATE(67)] = 1890,
  [SMALL_STATE(68)] = 1908,
  [SMALL_STATE(69)] = 1926,
  [SMALL_STATE(70)] = 1944,
  [SMALL_STATE(71)] = 1962,
  [SMALL_STATE(72)] = 1975,
  [SMALL_STATE(73)] = 1988,
  [SMALL_STATE(74)] = 2001,
  [SMALL_STATE(75)] = 2011,
  [SMALL_STATE(76)] = 2019,
  [SMALL_STATE(77)] = 2029,
  [SMALL_STATE(78)] = 2037,
  [SMALL_STATE(79)] = 2047,
  [SMALL_STATE(80)] = 2057,
  [SMALL_STATE(81)] = 2067,
  [SMALL_STATE(82)] = 2077,
  [SMALL_STATE(83)] = 2087,
  [SMALL_STATE(84)] = 2097,
  [SMALL_STATE(85)] = 2105,
  [SMALL_STATE(86)] = 2112,
  [SMALL_STATE(87)] = 2119,
  [SMALL_STATE(88)] = 2126,
  [SMALL_STATE(89)] = 2131,
  [SMALL_STATE(90)] = 2138,
  [SMALL_STATE(91)] = 2145,
  [SMALL_STATE(92)] = 2152,
  [SMALL_STATE(93)] = 2159,
  [SMALL_STATE(94)] = 2166,
  [SMALL_STATE(95)] = 2171,
  [SMALL_STATE(96)] = 2178,
  [SMALL_STATE(97)] = 2185,
  [SMALL_STATE(98)] = 2189,
  [SMALL_STATE(99)] = 2193,
  [SMALL_STATE(100)] = 2197,
  [SMALL_STATE(101)] = 2201,
  [SMALL_STATE(102)] = 2205,
  [SMALL_STATE(103)] = 2209,
  [SMALL_STATE(104)] = 2213,
  [SMALL_STATE(105)] = 2217,
  [SMALL_STATE(106)] = 2221,
  [SMALL_STATE(107)] = 2225,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(103),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(17),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(106),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(26),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(16),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(91),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(31),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(31),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_list, 2),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_list, 3),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2, .production_id = 1),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 2, .production_id = 1),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [151] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 1),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 1),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [169] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_statement, 3),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_statement, 3),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefix_expression, 2, .production_id = 2),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_prefix_expression, 2, .production_id = 2),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, .production_id = 6),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, .production_id = 6),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_statement, 4, .production_id = 7),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_statement, 4, .production_id = 7),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_statement, 2),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_statement, 2),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 5, .production_id = 9),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expression, 5, .production_id = 9),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 2, .production_id = 3),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expression, 2, .production_id = 3),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized_expression, 3),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 3),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 3),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 7, .production_id = 12),
  [223] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expression, 7, .production_id = 12),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 5),
  [227] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 5),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_literal, 3, .production_id = 5),
  [231] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_literal, 3, .production_id = 5),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 2),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 4),
  [239] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 4),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [249] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [253] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [255] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement_list, 1),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [259] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [261] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement_list, 2),
  [263] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__statement_list_repeat1, 2), SHIFT_REPEAT(8),
  [266] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_list_repeat1, 2), SHIFT_REPEAT(8),
  [269] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__statement_list_repeat1, 2),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_declaration_repeat1, 2, .production_id = 11),
  [273] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_declaration_repeat1, 2, .production_id = 11), SHIFT_REPEAT(104),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__statement_list_repeat1, 2),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2),
  [280] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2), SHIFT_REPEAT(87),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_declaration, 1, .production_id = 4),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [297] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(29),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_declaration, 2, .production_id = 8),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [310] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_declaration_repeat1, 2, .production_id = 10),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [314] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [320] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 4),
  [322] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2),
  [324] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [332] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_monkey(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
